// ===========================================================================
//  model.stan - hierarchical ordinal regression of review rating on the
//               principal components of a text embedding
// ===========================================================================
//
//  READ THIS FIRST (the statistical argument, before any code)
//  ---------------------------------------------------------------------
//  Each review was generated by an LLM from a KNOWN star rating y in 1..5, for
//  a known product topic j in 1..25. We then embedded the text and reduced the
//  embedding to K principal components x. The question is not "can we predict
//  the rating" - by construction we can. The question is:
//
//        does the strength of the text -> rating relationship
//        differ between product topics, and by how much?
//
//  We designed the answer to be YES: topics were assigned an "expressiveness"
//  level, so reviewers in some topics state their verdict outright and in
//  others only imply it. We therefore know the truth and can check whether the
//  model recovers it. That is what makes this a simulation study rather than a
//  demonstration.
//
//  Three modelling decisions follow from that, and each is defended below:
//    1. the outcome is ORDINAL, so we use an ordered-logistic likelihood;
//    2. topics are exchangeable draws from a population, so their intercepts
//       and slopes are MODELLED HIERARCHICALLY rather than as 25 fixed effects;
//    3. only the first few PC slopes are allowed to vary by topic, because
//       25 topics x 30 slopes is more variance than 50k observations can pin
//       down, and the design put the heterogeneity in the leading PCs anyway.
//
//  ---------------------------------------------------------------------
//  THE MODEL, in words
//
//    For review n in topic j = topic[n], form a linear predictor
//
//        eta[n] = x[n] . beta                      <- population-level effect
//               + u[1, j]                          <- this topic's intercept shift
//               + sum_{p=1..P} u[p+1, j] * x[n,p]  <- this topic's extra slope
//
//    and then
//
//        y[n] ~ ordered_logistic(eta[n], c)
//
//    where c is a vector of 4 ordered cutpoints separating the 5 rating
//    categories. The topic-level vector u[, j] (length P+1) is drawn from a
//    multivariate normal centred at zero with scales tau and correlation
//    matrix Omega. Centring u at zero is what makes beta interpretable as the
//    AVERAGE effect across topics, and u[, j] a deviation from it.
// ===========================================================================

data {
  int<lower=1> N;                       // number of reviews
  int<lower=1> J;                       // number of topics (25)
  int<lower=1> K;                       // number of PCs used as predictors (30)
  int<lower=1, upper=K> P;              // how many of those get topic-varying
                                        //   slopes (3 = PC1..PC3)
  int<lower=2> C;                       // number of ordered categories (5)

  array[N] int<lower=1, upper=J> topic; // which topic each review belongs to
  array[N] int<lower=1, upper=C> y;     // the star rating, 1..C
  matrix[N, K] x;                       // PC scores. MUST be standardised
                                        //   before they reach Stan - the
                                        //   priors below assume unit scale.
}

transformed data {
  int M = P + 1;                        // length of each topic's random-effect
                                        //   vector: 1 intercept + P slopes
}

parameters {
  // ---- population-level (what most people would call "fixed effects") ------
  vector[K] beta;                       // average effect of each PC on the
                                        //   log-odds of a higher rating

  // ---- cutpoints ----------------------------------------------------------
  // `ordered` is a Stan type that enforces c[1] < c[2] < ... < c[C-1] by
  // construction. Without it the likelihood is invariant to relabelling the
  // cutpoints and the sampler would wander between equivalent modes.
  ordered[C - 1] c;

  // ---- topic-level effects, NON-CENTRED -----------------------------------
  // We sample standardised deviates z_u and rescale them, rather than sampling
  // u directly. Why: when tau is small the "centred" parameterisation creates
  // a funnel-shaped posterior that HMC cannot traverse (Neal's funnel), which
  // shows up as divergent transitions. The non-centred form makes the geometry
  // roughly independent of tau. This is standard practice for hierarchical
  // models with modest group counts, and J = 25 is squarely in that regime.
  matrix[M, J] z_u;
  vector<lower=0>[M] tau;               // between-topic SD of each element
  cholesky_factor_corr[M] L_Omega;      // correlation among them (Cholesky)
}

transformed parameters {
  // u[, j] is topic j's deviation vector: row 1 is its intercept shift, rows
  // 2..M are its extra slopes on PC1..PC_P.
  //
  // diag_pre_multiply(tau, L_Omega) is the Cholesky factor of the covariance
  // matrix diag(tau) * Omega * diag(tau). Multiplying it by standard normal
  // deviates z_u yields draws with exactly that covariance - the non-centred
  // trick for the multivariate case.
  matrix[M, J] u = diag_pre_multiply(tau, L_Omega) * z_u;
}

model {
  // ---- priors -------------------------------------------------------------
  // These are weakly informative on the LOG-ODDS scale, which is the scale
  // that matters here, and they assume x has been standardised.

  // A one-SD move along a PC shifting the log-odds by more than about 2 (an
  // odds ratio of ~7) would be a very strong effect for a single component.
  // normal(0, 1) puts ~95% of prior mass inside +/-2 and still allows more.
  beta ~ normal(0, 1);

  // Cutpoints. On the logit scale +/-2.5 corresponds to cumulative
  // probabilities of about 8% and 92%, so normal(0, 2.5) comfortably spans
  // every plausible way five categories could be spread out, without being
  // flat (a flat prior on cutpoints leaks prior mass into absurd regions and
  // slows warmup).
  //   NOTE - a more refined alternative is the induced Dirichlet prior, which
  //   places a Dirichlet(1,...,1) prior on the implied category probabilities
  //   and transforms to cutpoints. It is better calibrated when categories are
  //   very unbalanced. We chose the simpler normal prior because our design is
  //   balanced by construction (equal numbers per rating) and because the
  //   simpler form is far easier to explain. If you rerun this on real,
  //   skewed rating data, switch to the induced Dirichlet.
  c ~ normal(0, 2.5);

  // Between-topic SDs. Half-normal (the <lower=0> declaration truncates it).
  // Scale 1 says: topic-to-topic variation of more than ~2 on the log-odds
  // scale is unlikely but not excluded. Crucially this prior does NOT force
  // tau away from zero, so the model is free to conclude "no heterogeneity" -
  // which is exactly what we need it to be able to say on the CONTROL arm.
  tau ~ normal(0, 1);

  // LKJ(2) mildly favours lower correlations, discouraging the model from
  // inventing near-perfect dependence between a topic's intercept and its
  // slopes on the strength of 25 groups. LKJ(1) would be uniform over
  // correlation matrices; 2 is the conventional weakly-regularising choice.
  L_Omega ~ lkj_corr_cholesky(2);

  // Standardised deviates. This line plus the transformed-parameters block is
  // what makes u multivariate normal with covariance diag(tau) Omega diag(tau).
  to_vector(z_u) ~ std_normal();

  // ---- likelihood ---------------------------------------------------------
  {
    // Population-level part for every observation at once (matrix-vector
    // product, far faster than looping).
    vector[N] eta = x * beta;

    // Add each topic's own intercept and slope deviations.
    for (n in 1:N) {
      int j = topic[n];
      eta[n] += u[1, j];                          // intercept shift
      for (p in 1:P)
        eta[n] += u[p + 1, j] * x[n, p];          // extra slope on PC p
    }

    // Note there is NO global intercept in eta. With an ordered-logistic
    // likelihood a global intercept is not identified: adding a constant to
    // eta and the same constant to every cutpoint leaves the likelihood
    // unchanged. The cutpoints absorb the overall location. The topic
    // intercepts u[1, ] remain identified because their prior pins their
    // mean at zero.
    y ~ ordered_logistic(eta, c);
  }
}

generated quantities {
  // ---- what the workshop actually looks at --------------------------------

  // Topic j's TOTAL slope on PC p: the population effect plus its own
  // deviation. This is the quantity the Block 4 interpretation plots, and the
  // one where partial pooling is visible - topics with few observations get
  // pulled toward beta[p].
  matrix[P, J] slope_by_topic;

  // Between-topic SD of the PC1 slope. This single number IS the research
  // question: "does the text -> rating relationship vary by topic?"
  // On the control arm we expect its posterior to pile up near zero.
  real tau_slope_pc1 = tau[2];

  // Correlation matrix, reconstructed from its Cholesky factor, for anyone who
  // wants to ask whether topics with higher baseline ratings also have
  // steeper slopes.
  matrix[P + 1, P + 1] Omega = multiply_lower_tri_self_transpose(L_Omega);

  // Pointwise log-likelihood, so loo::loo() can do PSIS-LOO model comparison
  // (e.g. this model versus one without varying slopes).
  vector[N] log_lik;

  {
    vector[N] eta = x * beta;
    for (n in 1:N) {
      int j = topic[n];
      eta[n] += u[1, j];
      for (p in 1:P)
        eta[n] += u[p + 1, j] * x[n, p];
    }
    for (n in 1:N)
      log_lik[n] = ordered_logistic_lpmf(y[n] | eta[n], c);

    for (p in 1:P)
      for (j in 1:J)
        slope_by_topic[p, j] = beta[p] + u[p + 1, j];
  }
}

// ===========================================================================
//  CHOICES I AM NOT FULLY SURE ABOUT - flagged deliberately rather than hidden
//  ---------------------------------------------------------------------
//  1. PCs as predictors. Principal components are chosen to maximise variance
//     in the embedding, NOT to be relevant to the rating. Nothing guarantees
//     the rating signal lives in the leading 30. It empirically does here, but
//     a supervised reduction (PLS) or penalised regression on the full
//     embedding would be the better tool if prediction were the goal. We use
//     PCs because they are familiar, unsupervised, and keep the model small
//     enough to fit in a workshop.
//
//  2. Which slopes vary. We let PC1..PC3 vary by topic and pool the remaining
//     27. That is a judgement call, defensible because the designed
//     heterogeneity is about overall expressiveness (which should load on
//     leading components) and because 25 x 30 varying slopes would be badly
//     under-identified. It is still an assumption, and a reviewer would be
//     right to ask what happens with P = 5.
//
//  3. Proportional odds. ordered_logistic assumes ONE set of slopes shifts all
//     cutpoints together. If, say, PC1 separated 1-star from everything else
//     but did nothing among 3/4/5 stars, this model would misfit. Worth
//     checking with a posterior predictive check on the category counts; the
//     escape hatch is a category-specific (non-proportional) model, which is
//     considerably heavier.
//
//  4. Independence. Reviews are modelled as conditionally independent given
//     topic. They were generated independently, so this is true BY
//     CONSTRUCTION here - but it would be a strong assumption on real scraped
//     data, where reviews of the same product share an author pool, a time
//     period, and a moderation policy.
// ===========================================================================
